spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dot?serverTimezone=Asia/Seoul
    username: root
    password: kkkimsehyen7941
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:dotdot_gcs.json
        project-id: dotdot-prod
        bucket: dotdot-bucket

security:
  jwt:
    token:
      key: aVeryStrongAndLongEnoughSecretKey123456
      expire-length: 1800000